#!/bin/bash

echo "🎯 Element Key Binder - Testing Guide"
echo "====================================="
echo ""
echo "1. Install the extension:"
echo "   - Open Chrome and go to chrome://extensions/"
echo "   - Enable Developer Mode (top right)"
echo "   - Click 'Load unpacked' and select this folder"
echo ""
echo "2. Test the extension:"
echo "   - Open test-page.html in Chrome"
echo "   - Open Developer Tools (F12) and check Console tab"
echo "   - Click the extension icon in the toolbar"
echo "   - Click 'Start Element Selection'"
echo "   - Look for console messages"
echo ""
echo "3. Debug checklist:"
echo "   - Extension icon should appear in toolbar"
echo "   - Popup should open when clicked"
echo "   - Console should show 'Element Key Binder: Content script loaded'"
echo "   - Console should show tab ID when popup opens"
echo "   - Console should show 'Starting element selection' when button clicked"
echo ""
echo "Opening test page..."
open test-page.html
